### ISSUE TITLE
apparent java related error when reading mzXML

### ISSUE THREAD

**Issue by whitleyo** [kaichengub/GlycoPAT#1]
I'm running matlab scripts using glycopat functions on a cluster.

When I try to run GlycoPAT's scoreAllSpectra function using an mzXML file I make via ProteoWizard's msconvert tool, I get what appear to be java related errors, but the mzXML file appears to be read into an mzXML object, and scoreAllSpectra seems to proceed as normal without throwing any errors. Specifically, for scoreAllSpectra, I used an mzXML file generated by proteowizard from the 4ProteinMix_02.raw file downloaded from PRIDE (PXD006031), and used the standard N-glycan library plus methionine oxidation, and the standard fixed ptm text file. In the process, I got these error messages, which I never saw when using your MZXML_4Protein_CID_example.mzXML file:

<indexOffset> not found!!!
</indexOffset> not found!!!
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at org.systemsbiology.jrap.MSXMLParser.<init>(MSXMLParser.java:241)
java.io.IOException: Invalid argument
        at java.io.FileInputStream.skip(Native Method)
        at org.systemsbiology.jrap.MSXMLParser.<init>(MSXMLParser.java:259)
<indexOffset> not found!!!
</indexOffset> not found!!!
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at org.systemsbiology.jrap.MSXMLParser.<init>(MSXMLParser.java:241)
        at org.systemsbiology.jrap.extension.ExtMSXMLParser.<init>(ExtMSXMLParser.java:21)
java.io.IOException: Invalid argument
        at java.io.FileInputStream.skip(Native Method)
        at org.systemsbiology.jrap.MSXMLParser.<init>(MSXMLParser.java:259)
        at org.systemsbiology.jrap.extension.ExtMSXMLParser.<init>(ExtMSXMLParser.java:21)

Additionally, these messages are printed to my output file (i.e. what matlab would normally print to the console):

exception:java.lang.StringIndexOutOfBoundsException: String index out of range: -1
File exception:java.io.IOException: Invalid argument
exception:java.lang.StringIndexOutOfBoundsException: String index out of range: -1
File exception:java.io.IOException: Invalid argument

I tried using the same mzXML file in the readmzXML function, and got the same messages. As far as I could tell from reading the MZXML_4Protein_CID_example.mzXML file, your example used 64 bit precision and zlib compression when being made via proteowizard, and I tried to do the same thing.

Note that scoreAllSpectra does not return an error and seems to be identifying glycopeptides, as seen in this bit of my output file:

i =
       14937
scan number: 14937
possible glycopeptide:
SmallGlyPep =
     []

i =
       14938
scan number: 14938
possible glycopeptide:
SmallGlyPep =
  cell
    'VVHAVEVALATFNAESN{n{n{h{h{n}}{h{n}{n{h}}}}}}GSYLQLVEISR'

Any ideas as to what could be happening here? I should also note that my script didn't finish through all scans before my job was killed for going over allocated wall time.

Thanks for your help.

**Comment by kaichengub** [comment]
This error is due to incorrect setting of JRAP library path. 
Solution: install GlycoPAT by running "installglycopat" again or by running:
"javaaddpath(_JRAPpath\jrap-ext-1.2.jar_)" in command window.
